### ISSUE TITLE
six and Python3 support

### ISSUE THREAD

**Issue by eeaston** [man-group/pkglib#27]
Python 3 support was added in by the welcome efforts of Steppan and Ed Catmur, but it's become problematic. The Six library is a great tool for resolving these things but it's tricky to use a dependency as pkglib sits at the bottom of the stack next to setuptools and needs it before it can function at all. 
As Six is a one-file library it is designed to be included inside other libraries for this very reason, I propose including it in the source of pkglib, as pkglib.six. Thoughts, @Wilfred ?

**Comment by eeaston** [comment]
An alternative to this could also be to include it in the source dist as a standalone module on the sys.path, and also included in setup_requires. 
This way pkglib can be bootstrapped from an empty environment when running from source, and will install six from pypi first when installing from an egg/whl.

**Comment by Wilfred** [comment]
Hmm, it's probably the best option. I'm a little nervous about including other libraries as it's very tempting to modify them, but I can't really see an alternative here.

Tests are currently failing: https://travis-ci.org/ahlmss/pkglib/builds/21114677 because our six monkey-patches provided `urlparse` and `ExitStack` in different places to upstream six. If we just have the latest six, the need for those monkey-patches (internally and in the public release) disappear.

We also have the problem internally that there are packages whose dependencies state `six==1.3.0`, so we haven't been able to move to six 1.4+ here either. I may have to hunt them down and fix them.

So overall, an up-to-date, unmodified copy of six sounds good. It'd be less pain than our current situation.

**Comment by Wilfred** [comment]
Fixed in #28.
